#!/usr/bin/env bash
# Render Formula/nexql-mcp.rb from a release tag + the vendor tarball SHA256s.
#
# This only *renders* the formula (for attaching as a release asset / for a
# tap-repo maintainer to copy in) — it does not push to a homebrew-tap repo,
# which would need write access to a separate repository this one doesn't
# control.
#
# Usage:
#   ./scripts/render-homebrew-formula.sh <version> <dist-artifacts-dir> <output-file>
#
# <dist-artifacts-dir> must contain, for each of darwin-arm64/darwin-x64/
# linux-arm64/linux-x64:
#   nexql-mcp-v<version>-vendor-<vendor>.tar.gz.sha256
# (exactly what the release workflow's "build" job already produces).
set -euo pipefail

VERSION="${1:?version required (e.g. 0.2.0)}"
DIST_DIR="${2:?dist-artifacts dir required}"
OUT_FILE="${3:?output file required}"

TAG="v${VERSION}"

sha_for() {
  local vendor="$1"
  local f="$DIST_DIR/nexql-mcp-${TAG}-vendor-${vendor}.tar.gz.sha256"
  test -f "$f" || { echo "missing $f" >&2; exit 1; }
  awk '{print $1}' "$f"
}

DARWIN_ARM64_SHA="$(sha_for darwin-arm64)"
DARWIN_X64_SHA="$(sha_for darwin-x64)"
LINUX_ARM64_SHA="$(sha_for linux-arm64)"
LINUX_X64_SHA="$(sha_for linux-x64)"

mkdir -p "$(dirname "$OUT_FILE")"
cat > "$OUT_FILE" <<RUBY
# Generated by scripts/render-homebrew-formula.sh for nexql-mcp ${TAG}.
# Copy into a homebrew-tap repo as Formula/nexql-mcp.rb.
class NexqlMcp < Formula
  desc "Standalone Postgres MCP server — schema-aware, read-only by default"
  homepage "https://github.com/NexQL-OSS/mcp"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NexQL-OSS/mcp/releases/download/${TAG}/nexql-mcp-${TAG}-vendor-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM64_SHA}"
    else
      url "https://github.com/NexQL-OSS/mcp/releases/download/${TAG}/nexql-mcp-${TAG}-vendor-darwin-x64.tar.gz"
      sha256 "${DARWIN_X64_SHA}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/NexQL-OSS/mcp/releases/download/${TAG}/nexql-mcp-${TAG}-vendor-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64_SHA}"
    else
      url "https://github.com/NexQL-OSS/mcp/releases/download/${TAG}/nexql-mcp-${TAG}-vendor-linux-x64.tar.gz"
      sha256 "${LINUX_X64_SHA}"
    end
  end

  def install
    bin.install Dir["*/nexql-mcp"].first => "nexql-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nexql-mcp --version")
  end
end
RUBY

echo "Rendered $OUT_FILE"
